// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfR-W6lD1wBZrQkrTsKevB9z052z1OHms',
    appId: '1:1192793751:web:381f4257406adc35bbbbd2',
    messagingSenderId: '1192793751',
    projectId: 'food-ordering-app-ebfca',
    authDomain: 'food-ordering-app-ebfca.firebaseapp.com',
    storageBucket: 'food-ordering-app-ebfca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSVAz0KtlgeX1JYn1lI9AnzQACCi8FmM',
    appId: '1:1192793751:android:bfa989f8d8e70ddabbbbd2',
    messagingSenderId: '1192793751',
    projectId: 'food-ordering-app-ebfca',
    storageBucket: 'food-ordering-app-ebfca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8nDbxUmUACineYeTf5ETdW-yBt7vGB-g',
    appId: '1:1192793751:ios:597ffd0a97d42687bbbbd2',
    messagingSenderId: '1192793751',
    projectId: 'food-ordering-app-ebfca',
    storageBucket: 'food-ordering-app-ebfca.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8nDbxUmUACineYeTf5ETdW-yBt7vGB-g',
    appId: '1:1192793751:ios:597ffd0a97d42687bbbbd2',
    messagingSenderId: '1192793751',
    projectId: 'food-ordering-app-ebfca',
    storageBucket: 'food-ordering-app-ebfca.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfR-W6lD1wBZrQkrTsKevB9z052z1OHms',
    appId: '1:1192793751:web:8fbb17225fe0ab89bbbbd2',
    messagingSenderId: '1192793751',
    projectId: 'food-ordering-app-ebfca',
    authDomain: 'food-ordering-app-ebfca.firebaseapp.com',
    storageBucket: 'food-ordering-app-ebfca.firebasestorage.app',
  );
}
